import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const angleCategory: CategoryDefinition = {
  id: "angle",
  name: "Angle",
  pluralName: "Angle",
  shortDescription: "Degrees, radians, gradians and more",
  description:
    "Angles measure rotation. Everyday and navigation contexts use degrees (360° per full turn); math and physics prefer radians (2π per turn) because they make calculus formulas simpler; surveying sometimes uses gradians (400 per turn); and military/artillery use \"mils\" (6400 per turn in the NATO system).",
  baseUnitId: "radian",
  icon: "RotateCw",
  linear: true,
  popularPairs: [
    ["degree", "radian"],
    ["radian", "degree"],
  ],
  units: [
    defineLinearUnit({
      id: "degree",
      categoryId: "angle",
      name: "Degree",
      symbol: "°",
      system: "other",
      factor: Math.PI / 180,
      aliases: ["degrees", "grado", "grados", "deg"],
    }),
    defineLinearUnit({
      id: "radian",
      categoryId: "angle",
      name: "Radian",
      symbol: "rad",
      system: "si",
      factor: 1,
      aliases: ["radians", "radian"],
      description: "SI derived unit of angle: the angle subtending an arc equal in length to the radius.",
    }),
    defineLinearUnit({
      id: "gradian",
      categoryId: "angle",
      name: "Gradian",
      symbol: "grad",
      system: "other",
      factor: Math.PI / 200,
      aliases: ["gradians", "gon"],
      description: "Divides a right angle into 100 units; a full turn is 400 gradians.",
    }),
    defineLinearUnit({
      id: "arcminute",
      categoryId: "angle",
      name: "Arcminute",
      symbol: "′",
      system: "other",
      factor: Math.PI / 10800,
      aliases: ["arcminutes", "minute of arc"],
    }),
    defineLinearUnit({
      id: "arcsecond",
      categoryId: "angle",
      name: "Arcsecond",
      symbol: "″",
      system: "other",
      factor: Math.PI / 648000,
      aliases: ["arcseconds", "second of arc"],
    }),
    defineLinearUnit({
      id: "turn",
      categoryId: "angle",
      name: "Turn",
      symbol: "tr",
      system: "other",
      factor: 2 * Math.PI,
      aliases: ["turns", "revolution", "revolutions", "vuelta"],
    }),
    defineLinearUnit({
      id: "angular-mil",
      categoryId: "angle",
      name: "Angular mil (NATO)",
      symbol: "mil",
      system: "other",
      factor: (2 * Math.PI) / 6400,
      aliases: ["mils", "nato mil"],
      description: "6400 mils per full turn; used in artillery and military targeting.",
    }),
  ],
};
