import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const areaCategory: CategoryDefinition = {
  id: "area",
  name: "Area",
  pluralName: "Area",
  shortDescription: "Square meters, acres, hectares and more",
  description:
    "Area measures the size of a two-dimensional surface. The square meter is the SI-derived base unit. Land is often measured in hectares (metric) or acres (imperial) — a hectare is exactly 10,000 m², while an acre is defined from the old English chain (a chain² is 1/10 acre).",
  baseUnitId: "square-meter",
  icon: "Square",
  linear: true,
  popularPairs: [
    ["hectare", "acre"],
    ["acre", "hectare"],
    ["square-meter", "square-foot"],
    ["square-foot", "square-meter"],
  ],
  units: [
    defineLinearUnit({
      id: "square-millimeter",
      categoryId: "area",
      name: "Square millimeter",
      symbol: "mm²",
      system: "metric",
      factor: 1e-6,
      aliases: ["square millimeters", "milimetro cuadrado"],
    }),
    defineLinearUnit({
      id: "square-centimeter",
      categoryId: "area",
      name: "Square centimeter",
      symbol: "cm²",
      system: "metric",
      factor: 1e-4,
      aliases: ["square centimeters", "centimetro cuadrado"],
    }),
    defineLinearUnit({
      id: "square-meter",
      categoryId: "area",
      name: "Square meter",
      symbol: "m²",
      system: "si",
      factor: 1,
      aliases: ["square meters", "metro cuadrado", "metros cuadrados"],
    }),
    defineLinearUnit({
      id: "square-kilometer",
      categoryId: "area",
      name: "Square kilometer",
      symbol: "km²",
      system: "metric",
      factor: 1e6,
      aliases: ["square kilometers", "kilometro cuadrado"],
    }),
    defineLinearUnit({
      id: "hectare",
      categoryId: "area",
      name: "Hectare",
      symbol: "ha",
      system: "metric",
      factor: 10000,
      aliases: ["hectares", "hectarea", "hectareas"],
      description: "Common unit for land area: exactly 10,000 square meters (100 m × 100 m).",
    }),
    defineLinearUnit({
      id: "square-inch",
      categoryId: "area",
      name: "Square inch",
      symbol: "in²",
      system: "imperial",
      factor: 0.00064516,
      aliases: ["square inches", "pulgada cuadrada"],
    }),
    defineLinearUnit({
      id: "square-foot",
      categoryId: "area",
      name: "Square foot",
      pluralName: "Square feet",
      symbol: "ft²",
      system: "imperial",
      factor: 0.09290304,
      aliases: ["square feet", "pie cuadrado"],
    }),
    defineLinearUnit({
      id: "square-yard",
      categoryId: "area",
      name: "Square yard",
      symbol: "yd²",
      system: "imperial",
      factor: 0.83612736,
      aliases: ["square yards", "yarda cuadrada"],
    }),
    defineLinearUnit({
      id: "acre",
      categoryId: "area",
      name: "Acre",
      symbol: "ac",
      system: "imperial",
      factor: 4046.8564224,
      aliases: ["acres"],
      description: "Traditional unit of land area, historically the area a yoke of oxen could plow in a day.",
    }),
    defineLinearUnit({
      id: "square-mile",
      categoryId: "area",
      name: "Square mile",
      symbol: "mi²",
      system: "imperial",
      factor: 2589988.110336,
      aliases: ["square miles", "milla cuadrada"],
    }),
    defineLinearUnit({
      id: "barn",
      categoryId: "area",
      name: "Barn",
      symbol: "b",
      system: "other",
      factor: 1e-28,
      aliases: ["barns"],
      description: "Extremely small unit used in nuclear and particle physics to express cross-sections.",
    }),
  ],
};
