import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const bitrateCategory: CategoryDefinition = {
  id: "bitrate",
  name: "Data Transfer Rate",
  pluralName: "Bitrate & Bandwidth",
  shortDescription: "bit/s, Mbps, Gbps, MB/s and more",
  description:
    "Data transfer rate (bitrate) measures how fast data moves, in bits or bytes per second. Internet plans are almost always advertised in bits per second (Mbps, Gbps), while file sizes and download managers show bytes (MB, GB). The two are easy to confuse: 1 byte = 8 bits, so a \"100 Mbps\" connection downloads at roughly 12.5 MB/s under ideal conditions, not 100 MB/s.",
  baseUnitId: "bit-per-second",
  icon: "Activity",
  linear: true,
  popularPairs: [
    ["megabit-per-second", "megabyte-per-second"],
    ["gigabit-per-second", "megabyte-per-second"],
  ],
  units: [
    defineLinearUnit({
      id: "bit-per-second",
      categoryId: "bitrate",
      name: "Bit per second",
      symbol: "bit/s",
      system: "si",
      factor: 1,
      aliases: ["bits per second", "bps"],
    }),
    defineLinearUnit({
      id: "kilobit-per-second",
      categoryId: "bitrate",
      name: "Kilobit per second",
      symbol: "kbit/s",
      system: "si",
      factor: 1000,
      aliases: ["kilobits per second", "kbps"],
    }),
    defineLinearUnit({
      id: "megabit-per-second",
      categoryId: "bitrate",
      name: "Megabit per second",
      symbol: "Mbit/s",
      system: "si",
      factor: 1e6,
      aliases: ["megabits per second", "mbps"],
    }),
    defineLinearUnit({
      id: "gigabit-per-second",
      categoryId: "bitrate",
      name: "Gigabit per second",
      symbol: "Gbit/s",
      system: "si",
      factor: 1e9,
      aliases: ["gigabits per second", "gbps"],
    }),
    defineLinearUnit({
      id: "terabit-per-second",
      categoryId: "bitrate",
      name: "Terabit per second",
      symbol: "Tbit/s",
      system: "si",
      factor: 1e12,
      aliases: ["terabits per second", "tbps"],
    }),
    defineLinearUnit({
      id: "byte-per-second",
      categoryId: "bitrate",
      name: "Byte per second",
      symbol: "B/s",
      system: "si",
      factor: 8,
      aliases: ["bytes per second"],
    }),
    defineLinearUnit({
      id: "kilobyte-per-second",
      categoryId: "bitrate",
      name: "Kilobyte per second",
      symbol: "KB/s",
      system: "si",
      factor: 8000,
      aliases: ["kilobytes per second"],
    }),
    defineLinearUnit({
      id: "megabyte-per-second",
      categoryId: "bitrate",
      name: "Megabyte per second",
      symbol: "MB/s",
      system: "si",
      factor: 8e6,
      aliases: ["megabytes per second"],
    }),
    defineLinearUnit({
      id: "gigabyte-per-second",
      categoryId: "bitrate",
      name: "Gigabyte per second",
      symbol: "GB/s",
      system: "si",
      factor: 8e9,
      aliases: ["gigabytes per second"],
    }),
  ],
};
