import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const dataCategory: CategoryDefinition = {
  id: "data",
  name: "Digital Storage",
  pluralName: "Digital Storage",
  shortDescription: "Bytes, KB, MB, GB, TB — decimal vs binary",
  description:
    "Digital storage has two competing conventions. Decimal units (kilobyte, megabyte, gigabyte...) follow SI prefixes: 1 KB = 1000 bytes. Binary units (kibibyte, mebibyte, gibibyte...) follow powers of two: 1 KiB = 1024 bytes. Operating systems and hard-drive manufacturers famously disagree on which to use — a drive sold as \"1 TB\" (10^12 bytes, decimal) shows up as about 931 GiB in an OS that reports binary units. This is why a file size and a drive's advertised capacity never quite match.",
  baseUnitId: "byte",
  icon: "HardDrive",
  linear: true,
  popularPairs: [
    ["gigabyte", "gibibyte"],
    ["megabyte", "mebibyte"],
    ["byte", "bit"],
  ],
  units: [
    defineLinearUnit({
      id: "bit",
      categoryId: "data",
      name: "Bit",
      symbol: "b",
      system: "si",
      factor: 0.125,
      aliases: ["bits"],
      description: "The smallest unit of digital information: a single binary 0 or 1.",
    }),
    defineLinearUnit({
      id: "nibble",
      categoryId: "data",
      name: "Nibble",
      symbol: "nibble",
      system: "other",
      factor: 0.5,
      aliases: ["nibbles", "nybble"],
      description: "Half a byte (4 bits) — enough to represent one hexadecimal digit.",
    }),
    defineLinearUnit({
      id: "byte",
      categoryId: "data",
      name: "Byte",
      symbol: "B",
      system: "si",
      factor: 1,
      aliases: ["bytes"],
      description: "8 bits. The fundamental unit of digital storage.",
    }),
    defineLinearUnit({
      id: "kilobyte",
      categoryId: "data",
      name: "Kilobyte",
      symbol: "KB",
      system: "si",
      factor: 1000,
      aliases: ["kilobytes"],
    }),
    defineLinearUnit({
      id: "megabyte",
      categoryId: "data",
      name: "Megabyte",
      symbol: "MB",
      system: "si",
      factor: 1e6,
      aliases: ["megabytes"],
    }),
    defineLinearUnit({
      id: "gigabyte",
      categoryId: "data",
      name: "Gigabyte",
      symbol: "GB",
      system: "si",
      factor: 1e9,
      aliases: ["gigabytes"],
    }),
    defineLinearUnit({
      id: "terabyte",
      categoryId: "data",
      name: "Terabyte",
      symbol: "TB",
      system: "si",
      factor: 1e12,
      aliases: ["terabytes"],
    }),
    defineLinearUnit({
      id: "petabyte",
      categoryId: "data",
      name: "Petabyte",
      symbol: "PB",
      system: "si",
      factor: 1e15,
      aliases: ["petabytes"],
    }),
    defineLinearUnit({
      id: "exabyte",
      categoryId: "data",
      name: "Exabyte",
      symbol: "EB",
      system: "si",
      factor: 1e18,
      aliases: ["exabytes"],
    }),
    defineLinearUnit({
      id: "zettabyte",
      categoryId: "data",
      name: "Zettabyte",
      symbol: "ZB",
      system: "si",
      factor: 1e21,
      aliases: ["zettabytes"],
    }),
    defineLinearUnit({
      id: "yottabyte",
      categoryId: "data",
      name: "Yottabyte",
      symbol: "YB",
      system: "si",
      factor: 1e24,
      aliases: ["yottabytes"],
    }),
    defineLinearUnit({
      id: "kibibyte",
      categoryId: "data",
      name: "Kibibyte",
      symbol: "KiB",
      system: "other",
      factor: 1024,
      aliases: ["kibibytes"],
      description: "Binary kilobyte: 2^10 bytes.",
    }),
    defineLinearUnit({
      id: "mebibyte",
      categoryId: "data",
      name: "Mebibyte",
      symbol: "MiB",
      system: "other",
      factor: 1024 ** 2,
      aliases: ["mebibytes"],
      description: "Binary megabyte: 2^20 bytes.",
    }),
    defineLinearUnit({
      id: "gibibyte",
      categoryId: "data",
      name: "Gibibyte",
      symbol: "GiB",
      system: "other",
      factor: 1024 ** 3,
      aliases: ["gibibytes"],
      description: "Binary gigabyte: 2^30 bytes.",
    }),
    defineLinearUnit({
      id: "tebibyte",
      categoryId: "data",
      name: "Tebibyte",
      symbol: "TiB",
      system: "other",
      factor: 1024 ** 4,
      aliases: ["tebibytes"],
    }),
    defineLinearUnit({
      id: "pebibyte",
      categoryId: "data",
      name: "Pebibyte",
      symbol: "PiB",
      system: "other",
      factor: 1024 ** 5,
      aliases: ["pebibytes"],
    }),
    defineLinearUnit({
      id: "exbibyte",
      categoryId: "data",
      name: "Exbibyte",
      symbol: "EiB",
      system: "other",
      factor: 1024 ** 6,
      aliases: ["exbibytes"],
    }),
    defineLinearUnit({
      id: "zebibyte",
      categoryId: "data",
      name: "Zebibyte",
      symbol: "ZiB",
      system: "other",
      factor: 1024 ** 7,
      aliases: ["zebibytes"],
    }),
    defineLinearUnit({
      id: "yobibyte",
      categoryId: "data",
      name: "Yobibyte",
      symbol: "YiB",
      system: "other",
      factor: 1024 ** 8,
      aliases: ["yobibytes"],
    }),
  ],
};
