import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const energyCategory: CategoryDefinition = {
  id: "energy",
  name: "Energy",
  pluralName: "Energy & Work",
  shortDescription: "Joules, kWh, calories, BTU and more",
  description:
    "Energy is the capacity to do work, and it shows up under very different names depending on the field: physics uses joules, electricity bills use kilowatt-hours, food labels use calories (technically kilocalories), and HVAC/heating uses BTU. They all measure the same underlying quantity and convert through the joule, the SI unit.",
  baseUnitId: "joule",
  icon: "Zap",
  linear: true,
  popularPairs: [
    ["kilowatt-hour", "joule"],
    ["calorie", "joule"],
    ["kilocalorie", "kilojoule"],
    ["btu", "joule"],
  ],
  units: [
    defineLinearUnit({
      id: "joule",
      categoryId: "energy",
      name: "Joule",
      symbol: "J",
      system: "si",
      factor: 1,
      aliases: ["joules"],
      description: "SI unit of energy: the work done by one newton over one meter.",
      source: "SI",
    }),
    defineLinearUnit({
      id: "kilojoule",
      categoryId: "energy",
      name: "Kilojoule",
      symbol: "kJ",
      system: "si",
      factor: 1000,
      aliases: ["kilojoules"],
    }),
    defineLinearUnit({
      id: "megajoule",
      categoryId: "energy",
      name: "Megajoule",
      symbol: "MJ",
      system: "si",
      factor: 1e6,
      aliases: ["megajoules"],
    }),
    defineLinearUnit({
      id: "watt-hour",
      categoryId: "energy",
      name: "Watt-hour",
      symbol: "Wh",
      system: "si",
      factor: 3600,
      aliases: ["watt hours", "watthour"],
    }),
    defineLinearUnit({
      id: "kilowatt-hour",
      categoryId: "energy",
      name: "Kilowatt-hour",
      symbol: "kWh",
      system: "si",
      factor: 3.6e6,
      aliases: ["kilowatt hours", "kwh"],
      description: "Standard billing unit for electricity: the energy used by a 1000 W load running for 1 hour.",
    }),
    defineLinearUnit({
      id: "megawatt-hour",
      categoryId: "energy",
      name: "Megawatt-hour",
      symbol: "MWh",
      system: "si",
      factor: 3.6e9,
      aliases: ["megawatt hours", "mwh"],
    }),
    defineLinearUnit({
      id: "calorie",
      categoryId: "energy",
      name: "Calorie",
      symbol: "cal",
      system: "other",
      factor: 4.184,
      aliases: ["calories", "caloria", "calorias", "small calorie"],
      description: "Thermochemical (small) calorie: energy to raise 1 gram of water by 1°C.",
    }),
    defineLinearUnit({
      id: "kilocalorie",
      categoryId: "energy",
      name: "Kilocalorie",
      symbol: "kcal",
      system: "other",
      factor: 4184,
      aliases: ["kilocalories", "food calorie", "Calorie", "calorias dietarias"],
      description: "The \"Calorie\" (capital C) on nutrition labels is actually a kilocalorie.",
    }),
    defineLinearUnit({
      id: "btu",
      categoryId: "energy",
      name: "British thermal unit",
      symbol: "BTU",
      system: "us",
      factor: 1055.05585262,
      aliases: ["btus", "british thermal units"],
      description: "International Table BTU. Common in HVAC and heating/cooling capacity ratings.",
    }),
    defineLinearUnit({
      id: "therm",
      categoryId: "energy",
      name: "Therm",
      symbol: "thm",
      system: "us",
      factor: 105505585.262,
      aliases: ["therms"],
      description: "US natural-gas billing unit, equal to 100,000 BTU.",
    }),
    defineLinearUnit({
      id: "electronvolt",
      categoryId: "energy",
      name: "Electronvolt",
      symbol: "eV",
      system: "other",
      factor: 1.602176634e-19,
      aliases: ["electronvolts", "ev"],
      description: "Energy gained by an electron accelerated through 1 volt. Used in particle physics.",
      source: "CODATA 2022",
    }),
    defineLinearUnit({
      id: "erg",
      categoryId: "energy",
      name: "Erg",
      symbol: "erg",
      system: "other",
      factor: 1e-7,
      aliases: ["ergs"],
      description: "CGS unit of energy.",
    }),
    defineLinearUnit({
      id: "foot-pound",
      categoryId: "energy",
      name: "Foot-pound",
      symbol: "ft·lb",
      system: "imperial",
      factor: 1.3558179483314004,
      aliases: ["foot pounds", "ft-lb"],
    }),
    defineLinearUnit({
      id: "horsepower-hour",
      categoryId: "energy",
      name: "Horsepower-hour",
      symbol: "hp·h",
      system: "imperial",
      factor: 2684519.5368856,
      aliases: ["horsepower hours"],
    }),
  ],
};
