import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const forceCategory: CategoryDefinition = {
  id: "force",
  name: "Force",
  pluralName: "Force",
  shortDescription: "Newtons, pound-force, dynes and more",
  description:
    "Force is what causes mass to accelerate (Newton's second law: F = m·a). The SI unit is the newton. Older systems define force units relative to standard gravity acting on a reference mass, which is why you'll see \"kilogram-force\" and \"pound-force\" — technically forces, even though they're named after mass units.",
  baseUnitId: "newton",
  icon: "ArrowDownToLine",
  linear: true,
  popularPairs: [
    ["newton", "pound-force"],
    ["kilogram-force", "newton"],
  ],
  units: [
    defineLinearUnit({
      id: "newton",
      categoryId: "force",
      name: "Newton",
      symbol: "N",
      system: "si",
      factor: 1,
      aliases: ["newtons"],
      description: "SI unit of force: the force to accelerate 1 kg at 1 m/s².",
      source: "SI",
    }),
    defineLinearUnit({
      id: "kilonewton",
      categoryId: "force",
      name: "Kilonewton",
      symbol: "kN",
      system: "si",
      factor: 1000,
      aliases: ["kilonewtons"],
    }),
    defineLinearUnit({
      id: "meganewton",
      categoryId: "force",
      name: "Meganewton",
      symbol: "MN",
      system: "si",
      factor: 1e6,
      aliases: ["meganewtons"],
    }),
    defineLinearUnit({
      id: "dyne",
      categoryId: "force",
      name: "Dyne",
      symbol: "dyn",
      system: "other",
      factor: 1e-5,
      aliases: ["dynes"],
      description: "CGS unit of force.",
    }),
    defineLinearUnit({
      id: "kilogram-force",
      categoryId: "force",
      name: "Kilogram-force",
      symbol: "kgf",
      system: "metric",
      factor: 9.80665,
      aliases: ["kgf", "kilopond", "kp"],
      description: "The force exerted by standard gravity on a 1 kg mass.",
    }),
    defineLinearUnit({
      id: "pound-force",
      categoryId: "force",
      name: "Pound-force",
      symbol: "lbf",
      system: "imperial",
      factor: 4.4482216152605,
      aliases: ["lbf", "libra fuerza"],
      description: "The force exerted by standard gravity on a 1 lb mass.",
    }),
    defineLinearUnit({
      id: "poundal",
      categoryId: "force",
      name: "Poundal",
      symbol: "pdl",
      system: "imperial",
      factor: 0.138254954376,
      aliases: ["poundals"],
      description: "Force needed to accelerate 1 pound-mass at 1 ft/s².",
    }),
  ],
};
