import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const lengthCategory: CategoryDefinition = {
  id: "length",
  name: "Length",
  pluralName: "Length & Distance",
  shortDescription: "Meters, feet, miles, inches and more",
  description:
    "Length (or distance) measures the extent of something from end to end. The metric system uses the meter as its base unit, defined since 1983 as the distance light travels in 1/299,792,458 of a second. The imperial and US customary systems instead build up from the inch, foot, yard and mile — units with historical roots in the human body and land measurement.",
  baseUnitId: "meter",
  icon: "Ruler",
  linear: true,
  popularPairs: [
    ["kilometer", "mile"],
    ["mile", "kilometer"],
    ["centimeter", "inch"],
    ["inch", "centimeter"],
    ["meter", "foot"],
    ["foot", "meter"],
  ],
  units: [
    defineLinearUnit({
      id: "nanometer",
      categoryId: "length",
      name: "Nanometer",
      symbol: "nm",
      system: "metric",
      factor: 1e-9,
      aliases: ["nanometers", "nanometro", "nanometros"],
      description: "One billionth of a meter. Used to measure wavelengths of light and atomic-scale distances.",
    }),
    defineLinearUnit({
      id: "micrometer",
      categoryId: "length",
      name: "Micrometer",
      symbol: "µm",
      system: "metric",
      factor: 1e-6,
      aliases: ["micrometers", "micron", "microns", "micrometro", "micrometros", "um"],
    }),
    defineLinearUnit({
      id: "millimeter",
      categoryId: "length",
      name: "Millimeter",
      symbol: "mm",
      system: "metric",
      factor: 1e-3,
      aliases: ["millimeters", "milimetro", "milimetros"],
    }),
    defineLinearUnit({
      id: "centimeter",
      categoryId: "length",
      name: "Centimeter",
      symbol: "cm",
      system: "metric",
      factor: 1e-2,
      aliases: ["centimeters", "centimetro", "centimetros"],
    }),
    defineLinearUnit({
      id: "meter",
      categoryId: "length",
      name: "Meter",
      symbol: "m",
      system: "si",
      factor: 1,
      aliases: ["meters", "metre", "metres", "metro", "metros"],
      description: "The SI base unit of length, defined via the speed of light.",
      source: "SI (BIPM)",
    }),
    defineLinearUnit({
      id: "kilometer",
      categoryId: "length",
      name: "Kilometer",
      symbol: "km",
      system: "metric",
      factor: 1000,
      aliases: ["kilometers", "kilometre", "kilometres", "kilometro", "kilometros"],
    }),
    defineLinearUnit({
      id: "inch",
      categoryId: "length",
      name: "Inch",
      symbol: "in",
      system: "imperial",
      factor: 0.0254,
      aliases: ["inches", "in.", "\"", "pulgada", "pulgadas"],
      source: "International yard and pound agreement (1959)",
    }),
    defineLinearUnit({
      id: "foot",
      categoryId: "length",
      name: "Foot",
      pluralName: "Feet",
      symbol: "ft",
      system: "imperial",
      factor: 0.3048,
      aliases: ["feet", "'", "pie", "pies"],
      source: "International yard and pound agreement (1959)",
    }),
    defineLinearUnit({
      id: "yard",
      categoryId: "length",
      name: "Yard",
      symbol: "yd",
      system: "imperial",
      factor: 0.9144,
      aliases: ["yards", "yarda", "yardas"],
    }),
    defineLinearUnit({
      id: "mile",
      categoryId: "length",
      name: "Mile",
      symbol: "mi",
      system: "imperial",
      factor: 1609.344,
      aliases: ["miles", "milla", "millas"],
    }),
    defineLinearUnit({
      id: "nautical-mile",
      categoryId: "length",
      name: "Nautical mile",
      symbol: "nmi",
      system: "other",
      factor: 1852,
      aliases: ["nautical miles", "milla nautica", "millas nauticas", "M"],
      description: "Used in air and marine navigation; approximates one minute of latitude.",
    }),
    defineLinearUnit({
      id: "light-year",
      categoryId: "length",
      name: "Light-year",
      symbol: "ly",
      system: "other",
      factor: 9.4607304725808e15,
      aliases: ["light years", "ano luz", "años luz"],
      description: "The distance light travels in vacuum in one Julian year.",
    }),
    defineLinearUnit({
      id: "astronomical-unit",
      categoryId: "length",
      name: "Astronomical unit",
      symbol: "AU",
      system: "other",
      factor: 1.495978707e11,
      aliases: ["astronomical units", "ua", "unidad astronomica"],
      description: "Approximately the mean distance between Earth and the Sun.",
      source: "IAU 2012 definition",
    }),
    defineLinearUnit({
      id: "parsec",
      categoryId: "length",
      name: "Parsec",
      symbol: "pc",
      system: "other",
      factor: 3.0856775814913673e16,
      aliases: ["parsecs"],
    }),
    defineLinearUnit({
      id: "point",
      categoryId: "length",
      name: "Point",
      symbol: "pt",
      system: "other",
      factor: 0.0254 / 72,
      aliases: ["points", "punto tipografico"],
      description: "Typographic unit: 1/72 of an inch (DTP point).",
    }),
    defineLinearUnit({
      id: "pica",
      categoryId: "length",
      name: "Pica",
      symbol: "pc(typ)",
      system: "other",
      factor: 0.0254 / 6,
      aliases: ["picas"],
      description: "Typographic unit: 12 points, or 1/6 of an inch.",
    }),
    defineLinearUnit({
      id: "mil",
      categoryId: "length",
      name: "Mil",
      pluralName: "Mils",
      symbol: "mil",
      system: "imperial",
      factor: 0.0000254,
      aliases: ["thou"],
      description: "Also called \"thou\": one thousandth of an inch. Common in manufacturing tolerances.",
    }),
    defineLinearUnit({
      id: "chain",
      categoryId: "length",
      name: "Chain",
      symbol: "ch",
      system: "imperial",
      factor: 20.1168,
      aliases: ["chains"],
    }),
    defineLinearUnit({
      id: "furlong",
      categoryId: "length",
      name: "Furlong",
      symbol: "fur",
      system: "imperial",
      factor: 201.168,
      aliases: ["furlongs"],
      description: "Traditionally 1/8 of a mile; still used in horse racing.",
    }),
    defineLinearUnit({
      id: "fathom",
      categoryId: "length",
      name: "Fathom",
      symbol: "ftm",
      system: "imperial",
      factor: 1.8288,
      aliases: ["fathoms", "braza"],
      description: "Traditionally used for measuring water depth.",
    }),
    defineLinearUnit({
      id: "league",
      categoryId: "length",
      name: "League",
      symbol: "lea",
      system: "imperial",
      factor: 4828.032,
      aliases: ["leagues", "legua", "leguas"],
      description: "Historically the distance a person could walk in about an hour (land league, 3 miles).",
    }),
  ],
};
