import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const massCategory: CategoryDefinition = {
  id: "mass",
  name: "Mass",
  pluralName: "Mass & Weight",
  shortDescription: "Kilograms, pounds, ounces, tonnes and more",
  description:
    "Mass measures the amount of matter in an object. In everyday language people say \"weight\" (kg, lb) when they mean mass — true weight is a force that depends on gravity, but for conversions on Earth's surface the distinction rarely matters. The kilogram is the SI base unit; the imperial/US system builds on the pound and ounce.",
  baseUnitId: "kilogram",
  icon: "Weight",
  linear: true,
  popularPairs: [
    ["kilogram", "pound"],
    ["pound", "kilogram"],
    ["gram", "ounce"],
    ["ounce", "gram"],
  ],
  units: [
    defineLinearUnit({
      id: "microgram",
      categoryId: "mass",
      name: "Microgram",
      symbol: "µg",
      system: "metric",
      factor: 1e-9,
      aliases: ["micrograms", "microgramo", "microgramos", "ug"],
    }),
    defineLinearUnit({
      id: "milligram",
      categoryId: "mass",
      name: "Milligram",
      symbol: "mg",
      system: "metric",
      factor: 1e-6,
      aliases: ["milligrams", "miligramo", "miligramos"],
    }),
    defineLinearUnit({
      id: "gram",
      categoryId: "mass",
      name: "Gram",
      symbol: "g",
      system: "metric",
      factor: 1e-3,
      aliases: ["grams", "gramo", "gramos"],
    }),
    defineLinearUnit({
      id: "kilogram",
      categoryId: "mass",
      name: "Kilogram",
      symbol: "kg",
      system: "si",
      factor: 1,
      aliases: ["kilograms", "kilogramo", "kilogramos", "kilo", "kilos"],
      description: "The SI base unit of mass, defined via the Planck constant since 2019.",
      source: "SI (BIPM)",
    }),
    defineLinearUnit({
      id: "tonne",
      categoryId: "mass",
      name: "Tonne",
      pluralName: "Tonnes",
      symbol: "t",
      system: "metric",
      factor: 1000,
      aliases: ["metric ton", "metric tons", "tonelada", "toneladas", "ton"],
    }),
    defineLinearUnit({
      id: "ounce",
      categoryId: "mass",
      name: "Ounce",
      symbol: "oz",
      system: "imperial",
      factor: 0.028349523125,
      aliases: ["ounces", "onza", "onzas"],
    }),
    defineLinearUnit({
      id: "pound",
      categoryId: "mass",
      name: "Pound",
      symbol: "lb",
      system: "imperial",
      factor: 0.45359237,
      aliases: ["pounds", "lbs", "libra", "libras"],
      source: "International yard and pound agreement (1959)",
    }),
    defineLinearUnit({
      id: "stone",
      categoryId: "mass",
      name: "Stone",
      pluralName: "Stone",
      symbol: "st",
      system: "imperial",
      factor: 6.35029318,
      aliases: ["stones", "piedra"],
      description: "Common in the UK and Ireland for body weight (1 stone = 14 pounds).",
    }),
    defineLinearUnit({
      id: "short-ton",
      categoryId: "mass",
      name: "Short ton",
      symbol: "sh tn",
      system: "us",
      factor: 907.18474,
      aliases: ["short tons", "us ton", "tonelada corta"],
      description: "US customary ton, equal to 2,000 pounds.",
    }),
    defineLinearUnit({
      id: "long-ton",
      categoryId: "mass",
      name: "Long ton",
      symbol: "long tn",
      system: "uk",
      factor: 1016.0469088,
      aliases: ["long tons", "imperial ton", "tonelada larga"],
      description: "UK/imperial ton, equal to 2,240 pounds.",
    }),
    defineLinearUnit({
      id: "atomic-mass-unit",
      categoryId: "mass",
      name: "Atomic mass unit",
      symbol: "u",
      system: "other",
      factor: 1.66053906892e-27,
      aliases: ["amu", "dalton", "unified atomic mass unit"],
      description: "Used in chemistry and physics to express atomic and molecular masses.",
      source: "CODATA 2022",
    }),
    defineLinearUnit({
      id: "carat",
      categoryId: "mass",
      name: "Carat",
      symbol: "ct",
      system: "other",
      factor: 0.0002,
      aliases: ["carats", "quilate", "quilates", "metric carat"],
      description: "Standard unit for gemstone weight.",
    }),
  ],
};
