import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const powerCategory: CategoryDefinition = {
  id: "power",
  name: "Power",
  pluralName: "Power",
  shortDescription: "Watts, kilowatts, horsepower and more",
  description:
    "Power is the rate at which energy is used or produced (energy per unit time). Electrical devices are rated in watts or kilowatts; engines are traditionally rated in horsepower — but \"horsepower\" itself has multiple slightly different definitions (mechanical vs metric), which is why the same engine can be advertised with a different hp number in Europe vs the US.",
  baseUnitId: "watt",
  icon: "Flame",
  linear: true,
  popularPairs: [
    ["kilowatt", "horsepower"],
    ["horsepower", "kilowatt"],
    ["watt", "btu-per-hour"],
  ],
  units: [
    defineLinearUnit({
      id: "watt",
      categoryId: "power",
      name: "Watt",
      symbol: "W",
      system: "si",
      factor: 1,
      aliases: ["watts", "vatio", "vatios"],
      description: "SI unit of power: one joule per second.",
      source: "SI",
    }),
    defineLinearUnit({
      id: "kilowatt",
      categoryId: "power",
      name: "Kilowatt",
      symbol: "kW",
      system: "si",
      factor: 1000,
      aliases: ["kilowatts", "kilovatio", "kilovatios"],
    }),
    defineLinearUnit({
      id: "megawatt",
      categoryId: "power",
      name: "Megawatt",
      symbol: "MW",
      system: "si",
      factor: 1e6,
      aliases: ["megawatts"],
    }),
    defineLinearUnit({
      id: "gigawatt",
      categoryId: "power",
      name: "Gigawatt",
      symbol: "GW",
      system: "si",
      factor: 1e9,
      aliases: ["gigawatts"],
    }),
    defineLinearUnit({
      id: "horsepower",
      categoryId: "power",
      name: "Horsepower (mechanical)",
      symbol: "hp",
      system: "imperial",
      factor: 745.6998715822702,
      aliases: ["mechanical horsepower", "hp(I)", "caballo de fuerza"],
      description: "Mechanical/imperial horsepower, defined as 550 ft·lb/s. Used in the US and UK.",
    }),
    defineLinearUnit({
      id: "metric-horsepower",
      categoryId: "power",
      name: "Metric horsepower (PS)",
      symbol: "PS",
      system: "metric",
      factor: 735.49875,
      aliases: ["ps", "cv", "caballo de vapor", "din horsepower"],
      description: "Continental European \"Pferdestärke\" / \"caballo de vapor\", defined as 75 kgf·m/s.",
    }),
    defineLinearUnit({
      id: "btu-per-hour",
      categoryId: "power",
      name: "BTU per hour",
      symbol: "BTU/h",
      system: "us",
      factor: 0.29307107017222,
      aliases: ["btu/hr", "btuh"],
      description: "Common rating for heaters, air conditioners and boilers in the US.",
    }),
    defineLinearUnit({
      id: "ton-of-refrigeration",
      categoryId: "power",
      name: "Ton of refrigeration",
      symbol: "TR",
      system: "us",
      factor: 3516.8528420667,
      aliases: ["refrigeration ton", "ton ac"],
      description: "Cooling power needed to freeze one short ton of water in 24 hours. Standard for air-conditioning capacity.",
    }),
  ],
};
