import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const pressureCategory: CategoryDefinition = {
  id: "pressure",
  name: "Pressure",
  pluralName: "Pressure",
  shortDescription: "Pascal, bar, PSI, atmospheres and more",
  description:
    "Pressure is force distributed over an area. Meteorology uses hectopascals/millibars, tire and hydraulics gauges use PSI or bar, scuba diving and vacuum work use atmospheres, and medical blood pressure and barometers still use mmHg — a unit that survives from mercury-column instruments even though most modern gauges are electronic.",
  baseUnitId: "pascal",
  icon: "Gauge",
  linear: true,
  popularPairs: [
    ["psi", "bar"],
    ["bar", "psi"],
    ["atm", "pascal"],
    ["kilopascal", "psi"],
  ],
  units: [
    defineLinearUnit({
      id: "pascal",
      categoryId: "pressure",
      name: "Pascal",
      symbol: "Pa",
      system: "si",
      factor: 1,
      aliases: ["pascals"],
      description: "SI unit of pressure: one newton per square meter.",
      source: "SI",
    }),
    defineLinearUnit({
      id: "kilopascal",
      categoryId: "pressure",
      name: "Kilopascal",
      symbol: "kPa",
      system: "si",
      factor: 1000,
      aliases: ["kilopascals"],
    }),
    defineLinearUnit({
      id: "megapascal",
      categoryId: "pressure",
      name: "Megapascal",
      symbol: "MPa",
      system: "si",
      factor: 1e6,
      aliases: ["megapascals"],
    }),
    defineLinearUnit({
      id: "bar",
      categoryId: "pressure",
      name: "Bar",
      symbol: "bar",
      system: "metric",
      factor: 100000,
      aliases: ["bars"],
      description: "Close to atmospheric pressure at sea level (1 bar ≈ 0.9869 atm). Widely used in Europe.",
    }),
    defineLinearUnit({
      id: "millibar",
      categoryId: "pressure",
      name: "Millibar",
      symbol: "mbar",
      system: "metric",
      factor: 100,
      aliases: ["millibars", "hectopascal", "hPa"],
      description: "Standard unit for atmospheric pressure in meteorology (equal to 1 hectopascal).",
    }),
    defineLinearUnit({
      id: "psi",
      categoryId: "pressure",
      name: "Pound per square inch",
      symbol: "psi",
      system: "imperial",
      factor: 6894.757293168,
      aliases: ["psig", "pounds per square inch", "libras por pulgada cuadrada"],
      description: "Standard unit for tire pressure and hydraulics in the US.",
    }),
    defineLinearUnit({
      id: "atm",
      categoryId: "pressure",
      name: "Standard atmosphere",
      symbol: "atm",
      system: "other",
      factor: 101325,
      aliases: ["atmospheres", "atmosfera", "atmosferas"],
      description: "Defined exactly as 101,325 Pa; approximates average sea-level air pressure.",
    }),
    defineLinearUnit({
      id: "torr",
      categoryId: "pressure",
      name: "Torr",
      symbol: "Torr",
      system: "other",
      factor: 133.322368421,
      aliases: ["torrs"],
      description: "Defined as 1/760 of a standard atmosphere; used in vacuum engineering.",
    }),
    defineLinearUnit({
      id: "mmhg",
      categoryId: "pressure",
      name: "Millimeter of mercury",
      symbol: "mmHg",
      system: "other",
      factor: 133.322387415,
      aliases: ["mm hg", "milimetros de mercurio"],
      description: "Traditional unit for blood pressure and barometric readings.",
    }),
    defineLinearUnit({
      id: "inhg",
      categoryId: "pressure",
      name: "Inch of mercury",
      symbol: "inHg",
      system: "us",
      factor: 3386.389,
      aliases: ["in hg", "pulgadas de mercurio"],
      description: "Used for barometric pressure in US aviation and weather reports.",
    }),
    defineLinearUnit({
      id: "kgf-per-cm2",
      categoryId: "pressure",
      name: "Kilogram-force per square centimeter",
      symbol: "kgf/cm²",
      system: "metric",
      factor: 98066.5,
      aliases: ["kg/cm2", "kg/cm²"],
    }),
    defineLinearUnit({
      id: "kgf-per-m2",
      categoryId: "pressure",
      name: "Kilogram-force per square meter",
      symbol: "kgf/m²",
      system: "metric",
      factor: 9.80665,
      aliases: ["kg/m2", "kg/m²"],
    }),
  ],
};
