import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const speedCategory: CategoryDefinition = {
  id: "speed",
  name: "Speed",
  pluralName: "Speed & Velocity",
  shortDescription: "km/h, mph, knots, Mach and more",
  description:
    "Speed measures distance covered per unit of time. Road speeds use km/h (most of the world) or mph (US, UK); aviation and marine navigation use knots (nautical miles per hour); and supersonic flight is measured in multiples of the speed of sound (Mach), which itself varies with air temperature and altitude.",
  baseUnitId: "meter-per-second",
  icon: "Gauge",
  linear: true,
  popularPairs: [
    ["kilometer-per-hour", "mile-per-hour"],
    ["mile-per-hour", "kilometer-per-hour"],
    ["knot", "kilometer-per-hour"],
  ],
  units: [
    defineLinearUnit({
      id: "meter-per-second",
      categoryId: "speed",
      name: "Meter per second",
      symbol: "m/s",
      system: "si",
      factor: 1,
      aliases: ["meters per second", "metros por segundo", "m/seg"],
    }),
    defineLinearUnit({
      id: "kilometer-per-hour",
      categoryId: "speed",
      name: "Kilometer per hour",
      symbol: "km/h",
      system: "metric",
      factor: 1 / 3.6,
      aliases: ["kilometers per hour", "kmh", "kph", "kilometros por hora"],
    }),
    defineLinearUnit({
      id: "mile-per-hour",
      categoryId: "speed",
      name: "Mile per hour",
      symbol: "mph",
      system: "imperial",
      factor: 0.44704,
      aliases: ["miles per hour", "millas por hora"],
    }),
    defineLinearUnit({
      id: "knot",
      categoryId: "speed",
      name: "Knot",
      symbol: "kn",
      system: "other",
      factor: 0.5144444444444445,
      aliases: ["knots", "nudo", "nudos", "kt"],
      description: "One nautical mile per hour. Standard unit in aviation and maritime navigation.",
    }),
    defineLinearUnit({
      id: "foot-per-second",
      categoryId: "speed",
      name: "Foot per second",
      symbol: "ft/s",
      system: "imperial",
      factor: 0.3048,
      aliases: ["feet per second", "fps", "pies por segundo"],
    }),
    defineLinearUnit({
      id: "mach",
      categoryId: "speed",
      name: "Mach (sea level, ISA)",
      symbol: "Ma",
      system: "other",
      factor: 340.3,
      aliases: ["mach number", "speed of sound"],
      description: "Multiple of the speed of sound in dry air at 15°C, sea level (ISA standard atmosphere, ≈340.3 m/s). Actual Mach number varies with temperature and altitude.",
    }),
    defineLinearUnit({
      id: "speed-of-light",
      categoryId: "speed",
      name: "Speed of light (fraction of c)",
      symbol: "c",
      system: "other",
      factor: 299792458,
      aliases: ["c", "light speed", "velocidad de la luz"],
      description: "Exact speed of light in vacuum, used to express relativistic speeds as a fraction of c.",
      source: "SI (defines the meter)",
    }),
  ],
};
