import { defineCustomUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

/**
 * Temperature is the canonical example of a NON-multiplicative unit category:
 * every scale except Kelvin has an offset, and some also have a different
 * step size per degree. Base unit is Kelvin because it has no offset itself,
 * which keeps every other formula a one-line affine transform.
 */
export const temperatureCategory: CategoryDefinition = {
  id: "temperature",
  name: "Temperature",
  pluralName: "Temperature",
  shortDescription: "Celsius, Fahrenheit, Kelvin and more",
  description:
    "Temperature scales are NOT simple multiples of each other — most have an offset (a different zero point) and some also have a different degree size. Celsius sets 0° at water's freezing point; Fahrenheit sets 0° at a brine mixture and uses a smaller degree; Kelvin starts at absolute zero with the same degree size as Celsius. Converting between scales always requires both a multiplication and an addition, never just a factor.",
  baseUnitId: "kelvin",
  icon: "Thermometer",
  linear: false,
  popularPairs: [
    ["celsius", "fahrenheit"],
    ["fahrenheit", "celsius"],
    ["celsius", "kelvin"],
    ["kelvin", "celsius"],
  ],
  units: [
    defineCustomUnit({
      id: "celsius",
      categoryId: "temperature",
      name: "Celsius",
      symbol: "°C",
      system: "si",
      toBase: (c) => c + 273.15,
      fromBase: (k) => k - 273.15,
      aliases: ["c", "centigrade", "celsius", "centigrados", "grados celsius"],
      description: "0 °C = freezing point of water, 100 °C = boiling point of water at sea level.",
      source: "SI",
    }),
    defineCustomUnit({
      id: "fahrenheit",
      categoryId: "temperature",
      name: "Fahrenheit",
      symbol: "°F",
      system: "us",
      toBase: (f) => ((f - 32) * 5) / 9 + 273.15,
      fromBase: (k) => ((k - 273.15) * 9) / 5 + 32,
      aliases: ["f", "fahrenheit", "grados fahrenheit"],
      description: "0 °F ≈ freezing point of brine, 32 °F = freezing point of water, 212 °F = boiling point of water.",
    }),
    defineCustomUnit({
      id: "kelvin",
      categoryId: "temperature",
      name: "Kelvin",
      symbol: "K",
      system: "si",
      toBase: (k) => k,
      fromBase: (k) => k,
      aliases: ["k", "kelvin", "kelvins"],
      description: "SI base unit of temperature. 0 K is absolute zero; the Kelvin degree is the same size as Celsius.",
      source: "SI (BIPM)",
    }),
    defineCustomUnit({
      id: "rankine",
      categoryId: "temperature",
      name: "Rankine",
      symbol: "°R",
      system: "us",
      toBase: (r) => (r * 5) / 9,
      fromBase: (k) => (k * 9) / 5,
      aliases: ["r", "rankine", "grados rankine"],
      description: "Absolute scale with Fahrenheit-sized degrees; 0 °R is absolute zero.",
    }),
    defineCustomUnit({
      id: "delisle",
      categoryId: "temperature",
      name: "Delisle",
      symbol: "°De",
      system: "other",
      toBase: (d) => 373.15 - (d * 2) / 3,
      fromBase: (k) => ((373.15 - k) * 3) / 2,
      aliases: ["de", "delisle", "grados delisle"],
      description: "Historical inverted scale: 0 °De is boiling water, 150 °De is freezing water.",
    }),
    defineCustomUnit({
      id: "newton-scale",
      categoryId: "temperature",
      name: "Newton",
      symbol: "°N",
      system: "other",
      toBase: (n) => (n * 100) / 33 + 273.15,
      fromBase: (k) => ((k - 273.15) * 33) / 100,
      aliases: ["n", "grados newton"],
      description: "Isaac Newton's own scale, rarely used today.",
    }),
    defineCustomUnit({
      id: "reaumur",
      categoryId: "temperature",
      name: "Réaumur",
      symbol: "°Ré",
      system: "other",
      toBase: (re) => (re * 5) / 4 + 273.15,
      fromBase: (k) => ((k - 273.15) * 4) / 5,
      aliases: ["re", "reaumur", "reamur", "grados reaumur"],
      description: "Historical European scale where water freezes at 0° and boils at 80°.",
    }),
    defineCustomUnit({
      id: "romer",
      categoryId: "temperature",
      name: "Rømer",
      symbol: "°Rø",
      system: "other",
      toBase: (ro) => ((ro - 7.5) * 40) / 21 + 273.15,
      fromBase: (k) => ((k - 273.15) * 21) / 40 + 7.5,
      aliases: ["ro", "romer", "roemer", "grados romer"],
      description: "18th-century Danish scale where water freezes at 7.5° and boils at 60°.",
    }),
  ],
};
