import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const timeCategory: CategoryDefinition = {
  id: "time",
  name: "Time",
  pluralName: "Time & Duration",
  shortDescription: "Seconds, minutes, hours, days, years and more",
  description:
    "Time units below the day (seconds, minutes, hours) are exact and universal. Months and years are NOT exact durations — a month can be 28 to 31 days, and a calendar year depends on leap years. This converter treats \"month\" and \"year\" as fixed AVERAGE durations (30.44 days and 365.25 days respectively) for duration math. For calendar-accurate date arithmetic — \"3 months from March 15\" — use the Date Difference guide instead of a fixed-factor conversion.",
  baseUnitId: "second",
  icon: "Clock",
  linear: true,
  popularPairs: [
    ["day", "hour"],
    ["hour", "minute"],
    ["week", "day"],
    ["year", "day"],
  ],
  units: [
    defineLinearUnit({
      id: "nanosecond",
      categoryId: "time",
      name: "Nanosecond",
      symbol: "ns",
      system: "si",
      factor: 1e-9,
      aliases: ["nanoseconds", "nanosegundo", "nanosegundos"],
    }),
    defineLinearUnit({
      id: "microsecond",
      categoryId: "time",
      name: "Microsecond",
      symbol: "µs",
      system: "si",
      factor: 1e-6,
      aliases: ["microseconds", "microsegundo", "microsegundos"],
    }),
    defineLinearUnit({
      id: "millisecond",
      categoryId: "time",
      name: "Millisecond",
      symbol: "ms",
      system: "si",
      factor: 1e-3,
      aliases: ["milliseconds", "milisegundo", "milisegundos"],
    }),
    defineLinearUnit({
      id: "second",
      categoryId: "time",
      name: "Second",
      symbol: "s",
      system: "si",
      factor: 1,
      aliases: ["seconds", "segundo", "segundos", "sec"],
      description: "The SI base unit of time, defined via the cesium atomic transition frequency.",
      source: "SI (BIPM)",
    }),
    defineLinearUnit({
      id: "minute",
      categoryId: "time",
      name: "Minute",
      symbol: "min",
      system: "si",
      factor: 60,
      aliases: ["minutes", "minuto", "minutos"],
    }),
    defineLinearUnit({
      id: "hour",
      categoryId: "time",
      name: "Hour",
      symbol: "h",
      system: "si",
      factor: 3600,
      aliases: ["hours", "hora", "horas", "hr"],
    }),
    defineLinearUnit({
      id: "day",
      categoryId: "time",
      name: "Day",
      symbol: "d",
      system: "si",
      factor: 86400,
      aliases: ["days", "dia", "dias"],
    }),
    defineLinearUnit({
      id: "week",
      categoryId: "time",
      name: "Week",
      symbol: "wk",
      system: "other",
      factor: 604800,
      aliases: ["weeks", "semana", "semanas"],
    }),
    defineLinearUnit({
      id: "month",
      categoryId: "time",
      name: "Month",
      symbol: "mo",
      system: "other",
      factor: 2629800, // 30.4375 days average (365.25 / 12)
      aliases: ["months", "mes", "meses"],
      description: "Average calendar month (365.25 days / 12 ≈ 30.44 days). Real months vary from 28 to 31 days.",
    }),
    defineLinearUnit({
      id: "year",
      categoryId: "time",
      name: "Year",
      symbol: "yr",
      system: "other",
      factor: 31557600, // Julian year: 365.25 days
      aliases: ["years", "ano", "anos", "año", "años"],
      description: "Julian year (365.25 days), the standard astronomical approximation used for unit conversion.",
    }),
    defineLinearUnit({
      id: "decade",
      categoryId: "time",
      name: "Decade",
      symbol: "dec",
      system: "other",
      factor: 315576000,
      aliases: ["decades", "decada", "decadas"],
    }),
    defineLinearUnit({
      id: "century",
      categoryId: "time",
      name: "Century",
      symbol: "c",
      system: "other",
      factor: 3155760000,
      aliases: ["centuries", "siglo", "siglos"],
    }),
    defineLinearUnit({
      id: "millennium",
      categoryId: "time",
      name: "Millennium",
      pluralName: "Millennia",
      symbol: "ka",
      system: "other",
      factor: 31557600000,
      aliases: ["millennia", "milenio", "milenios"],
    }),
  ],
};
