import { defineLinearUnit } from "../helpers";
import type { CategoryDefinition } from "../types";

export const volumeCategory: CategoryDefinition = {
  id: "volume",
  name: "Volume",
  pluralName: "Volume & Capacity",
  shortDescription: "Liters, gallons, cups, cubic meters and more",
  description:
    "Volume measures how much three-dimensional space something occupies. The metric system bases volume on the liter (1 liter = 1 cubic decimeter). US customary and Imperial (UK) systems both use gallons, quarts, pints and cups — but they are NOT the same size: a US gallon (3.785 L) is smaller than an Imperial gallon (4.546 L). Always check which system a recipe or spec is using.",
  baseUnitId: "liter",
  icon: "Beaker",
  linear: true,
  popularPairs: [
    ["liter", "us-gallon"],
    ["us-gallon", "liter"],
    ["milliliter", "us-fluid-ounce"],
    ["cubic-meter", "cubic-foot"],
  ],
  units: [
    defineLinearUnit({
      id: "milliliter",
      categoryId: "volume",
      name: "Milliliter",
      symbol: "mL",
      system: "metric",
      factor: 0.001,
      aliases: ["milliliters", "mililitro", "mililitros", "ml"],
    }),
    defineLinearUnit({
      id: "centiliter",
      categoryId: "volume",
      name: "Centiliter",
      symbol: "cL",
      system: "metric",
      factor: 0.01,
      aliases: ["centiliters", "centilitro", "centilitros"],
    }),
    defineLinearUnit({
      id: "deciliter",
      categoryId: "volume",
      name: "Deciliter",
      symbol: "dL",
      system: "metric",
      factor: 0.1,
      aliases: ["deciliters", "decilitro", "decilitros"],
    }),
    defineLinearUnit({
      id: "liter",
      categoryId: "volume",
      name: "Liter",
      symbol: "L",
      system: "metric",
      factor: 1,
      aliases: ["liters", "litre", "litres", "litro", "litros", "l"],
      description: "1 liter = 1 cubic decimeter = 1000 cubic centimeters.",
    }),
    defineLinearUnit({
      id: "cubic-millimeter",
      categoryId: "volume",
      name: "Cubic millimeter",
      symbol: "mm³",
      system: "metric",
      factor: 1e-6,
      aliases: ["cubic millimeters", "milimetro cubico"],
    }),
    defineLinearUnit({
      id: "cubic-centimeter",
      categoryId: "volume",
      name: "Cubic centimeter",
      symbol: "cm³",
      system: "metric",
      factor: 0.001,
      aliases: ["cubic centimeters", "cc", "centimetro cubico"],
    }),
    defineLinearUnit({
      id: "cubic-meter",
      categoryId: "volume",
      name: "Cubic meter",
      symbol: "m³",
      system: "si",
      factor: 1000,
      aliases: ["cubic meters", "metro cubico", "metros cubicos"],
    }),
    defineLinearUnit({
      id: "cubic-inch",
      categoryId: "volume",
      name: "Cubic inch",
      symbol: "in³",
      system: "imperial",
      factor: 0.016387064,
      aliases: ["cubic inches", "pulgada cubica"],
    }),
    defineLinearUnit({
      id: "cubic-foot",
      categoryId: "volume",
      name: "Cubic foot",
      pluralName: "Cubic feet",
      symbol: "ft³",
      system: "imperial",
      factor: 28.316846592,
      aliases: ["cubic feet", "pie cubico"],
    }),
    defineLinearUnit({
      id: "cubic-yard",
      categoryId: "volume",
      name: "Cubic yard",
      symbol: "yd³",
      system: "imperial",
      factor: 764.554857984,
      aliases: ["cubic yards", "yarda cubica"],
    }),
    defineLinearUnit({
      id: "us-gallon",
      categoryId: "volume",
      name: "US gallon",
      symbol: "gal (US)",
      system: "us",
      factor: 3.785411784,
      aliases: ["us gallons", "gallon", "gallons", "galon", "galones", "galon americano"],
      description: "US liquid gallon. Different from the UK imperial gallon (4.546 L).",
    }),
    defineLinearUnit({
      id: "us-quart",
      categoryId: "volume",
      name: "US quart",
      symbol: "qt (US)",
      system: "us",
      factor: 0.946352946,
      aliases: ["us quarts", "quart", "quarts", "cuarto galon"],
    }),
    defineLinearUnit({
      id: "us-pint",
      categoryId: "volume",
      name: "US pint",
      symbol: "pt (US)",
      system: "us",
      factor: 0.473176473,
      aliases: ["us pints", "pint", "pints", "pinta"],
    }),
    defineLinearUnit({
      id: "us-cup",
      categoryId: "volume",
      name: "US cup",
      symbol: "cup",
      system: "us",
      factor: 0.2365882365,
      aliases: ["us cups", "cups", "taza", "tazas"],
    }),
    defineLinearUnit({
      id: "us-fluid-ounce",
      categoryId: "volume",
      name: "US fluid ounce",
      symbol: "fl oz (US)",
      system: "us",
      factor: 0.0295735295625,
      aliases: ["us fluid ounces", "fluid ounce", "fluid ounces", "onza liquida"],
    }),
    defineLinearUnit({
      id: "us-tablespoon",
      categoryId: "volume",
      name: "US tablespoon",
      symbol: "tbsp",
      system: "us",
      factor: 0.0147867647813,
      aliases: ["us tablespoons", "tablespoon", "tablespoons", "cucharada", "cucharadas"],
    }),
    defineLinearUnit({
      id: "us-teaspoon",
      categoryId: "volume",
      name: "US teaspoon",
      symbol: "tsp",
      system: "us",
      factor: 0.00492892159375,
      aliases: ["us teaspoons", "teaspoon", "teaspoons", "cucharadita", "cucharaditas"],
    }),
    defineLinearUnit({
      id: "imperial-gallon",
      categoryId: "volume",
      name: "Imperial gallon",
      symbol: "gal (UK)",
      system: "uk",
      factor: 4.54609,
      aliases: ["imperial gallons", "uk gallon", "galon imperial"],
      description: "UK imperial gallon, used in the UK and some Commonwealth countries. Larger than the US gallon.",
    }),
    defineLinearUnit({
      id: "imperial-quart",
      categoryId: "volume",
      name: "Imperial quart",
      symbol: "qt (UK)",
      system: "uk",
      factor: 1.1365225,
      aliases: ["imperial quarts", "uk quart"],
    }),
    defineLinearUnit({
      id: "imperial-pint",
      categoryId: "volume",
      name: "Imperial pint",
      symbol: "pt (UK)",
      system: "uk",
      factor: 0.56826125,
      aliases: ["imperial pints", "uk pint"],
    }),
    defineLinearUnit({
      id: "imperial-fluid-ounce",
      categoryId: "volume",
      name: "Imperial fluid ounce",
      symbol: "fl oz (UK)",
      system: "uk",
      factor: 0.0284130625,
      aliases: ["imperial fluid ounces", "uk fluid ounce"],
    }),
    defineLinearUnit({
      id: "barrel-oil",
      categoryId: "volume",
      name: "Oil barrel",
      symbol: "bbl",
      system: "us",
      factor: 158.987294928,
      aliases: ["barrel", "barrels", "barril", "barriles", "oil barrels"],
      description: "Standard US oil-industry barrel (42 US gallons).",
    }),
  ],
};
